### ISSUE TITLE
Fix Last visit time column ordering

### ISSUE THREAD

**Issue by GabLeRoux** [GabLeRoux/webextensions-history-browser#4]
I'm not quite sure this is working correctly, kind of confusing right now so it's probably wrong :)
could be related to #3 too.

**Comment by jrobichaud** [comment]
When opening "History Browser" for the first time the ordering is correctly sorted by `Last Visit Time`.

However when clicking on another column to change to another ordering and then selecting `Last Visit Time` the ordering is broken.
